package org.roojai.tha.types.roojaigroundpartneragent.roojaiquote.extendedwarranty
public class THARGPAExtendedWarrantyCoreType{
	public static String CURRENT_GROUND_PARTNER_AGENT_URL_PORTAL=''
	public static Integer CURRENT_GROUND_PARTNER_AGENT_ACCOUNT_SOURCE=1
	public static String CURRENT_GROUND_PARTNER_AGENT_URL_PRODUCT_SELECT=''
	public static String CURRENT_GROUND_PARTNER_AGENT_URL_SKIP_LOGIN=''
	public static String CURRENT_GROUND_PARTNER_AGENT_USER=''
	public static String CURRENT_GROUND_PARTNER_AGENT_PASSWORD=''
	public static String CURRENT_GROUND_PARTNER_AGENT_LANGUAGE=''
	public static Boolean CURRENT_POLICY_DETAIL_1_SKIP_CALL_ME_NOW=false
	public static Boolean CURRENT_POLICY_DETAIL_1_SKIP_OTP=true
	public static Boolean CURRENT_SOCIAL_SKIP_RATING=false
	public static String CURRENT_QUOTATION_VEHICLE_OPPORTUNITY_NUMBER=''
	public static String CURRENT_QUOTATION_PAYMENT_METHOD=''
	public static String CURRENT_QUOTATION_PAYMENT_TRUE_MONEY_MOBILE_NO=''
	public static String CURRENT_QUOTATION_PAYMENT_TRUE_MONEY_EMAIL=''
	public static String CURRENT_QUOTATION_PAYMENT_TRUE_MONEY_SUCCESS_CASE=''
	public static String CURRENT_QUOTATION_PAYMENT_RABBIT_LINE_PAY_MOBILE_NO=''
	public static String CURRENT_QUOTATION_PAYMENT_RABBIT_LINE_PAY_EMAIL=''
	public static String CURRENT_QUOTATION_PAYMENT_RABBIT_LINE_PAY_SUCCESS_CASE=''
}