package org.roojai.tha.types.myaccount.newbiz
import com.kms.katalon.core.testdata.TestData
import com.kms.katalon.keyword.excel.ExcelKeywords as ExcelKeywords
import org.roojai.ignite.core.IGNUemaHelper as IGNUemaHelper
public class THAMyAccountNewbizMainFactory{
	public Boolean IsValid=false
	private lCaseList=[]
	public Integer CurrentCase=0
	public THAMyAccountNewbizMainFactory(TestData dataInput){
		super()
		this.initCaseList(dataInput)
	}
	public Boolean getIsValid(){
		return this.IsValid
	}
	public void setIsValid(Boolean isValid){
		//Do Nothing
		//this.IsValid=isValid
	}
	private void setlCaseList(java.lang.Object lCaseList){
		//Do Nothing
		//this.lCaseList=lCaseList
	}
	private java.lang.Object getlCaseList(){
		return lCaseList
	}
	public Integer getCurrentCase(){
		return this.CurrentCase
	}
	public void setCurrentCase(Integer currentCase){
		if(this.IsValid){
			if(currentCase<=this.lCaseList.size()){
				this.CurrentCase=currentCase
			}
		}
	}
	public Boolean validateDataInput(TestData dataInput){
		Boolean lreturn=false
		try{
			Integer dataColNum=dataInput.getColumnNumbers()
			Integer dataRowNum=dataInput.getRowNumbers()
			lreturn=(dataColNum>=THAMyAccountNewbizMainType.INPUT_DATA_COL_BEGIN)&&(dataRowNum>=THAMyAccountNewbizMainType.INPUT_DATA_ROW_END)
		}catch(Exception e){
			e.printStackTrace()
			return lreturn
		}
		return lreturn
	}
	public void initCaseList(TestData dataInput){
		Boolean isValid=this.validateDataInput(dataInput)
		try{
			this.lCaseList.clear()
			Integer dataColNum=dataInput.getColumnNumbers()
			Integer dataRowNum=dataInput.getRowNumbers()
			Integer dataColIndex=THAMyAccountNewbizMainType.INPUT_DATA_COL_BEGIN
			Integer dataRowIndex=THAMyAccountNewbizMainType.INPUT_DATA_ROW_BEGIN
			THAMyAccountNewbizMainType dataCase
			Map caseInput=[:]
			caseInput.clear()
			String cellVal=''
			for(dataColIndex=THAMyAccountNewbizMainType.INPUT_DATA_COL_BEGIN;dataColIndex<=dataColNum;dataColIndex++){
				dataCase=new THAMyAccountNewbizMainType()
				dataCase.initInput()
				dataCase.initOutput()
				caseInput.clear()
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('BaseUrl',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MaximizeMode',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('WithAuth',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('AuthUser',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('AuthPassword',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('Language',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPaymentToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPaymentOpenTermAndCondition',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPaymentChangeCreditCard',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPaymentMakePaymentCardOld',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPaymentMakePaymentCardNew',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuProfileToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuProfilePositiveCase',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileMaritalStatus',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfilePreferredLanguage',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileOccupation',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileAddressHouseBuildingNumber',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileAddressVillage',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileAddressSoiRoad',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileAddressPostcode',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileAddressProvince',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileAddressDistrict',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileAddressSubdistrict',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileTelephoneNumber',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('ProfileEmail',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyCardSelectProductMotor',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyCardSelectProductHealth',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailHistoryToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailDocDownloadToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailDocDownloadOpenInsuranceHandbookToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailPaymentToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailPaymentOpenTermAndConditionToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailTaxDeductionToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailTaxDeductionAccept',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailTaxDeductionEditToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailTaxDeductionEditHolderIsThai',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailTaxDeductionEditName',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailTaxDeductionEditSurname',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailTaxDeductionEditIdentificationNumber',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyDetailECareCardToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuPolicyCompulsoryBuyCardToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuClaimToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuClaimDetailNonClosureToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuClaimDetailClosureStatusToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuClaimDetailClosureStatusUpdate',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuDocDownloadToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuDocDownloadOpenInsuranceHandbook',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuDocDownloadCardToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportSubjectRenewalToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportSubjectPolicyToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportSubjectClaimToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportSubjectEnquiryClaimHandlerToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportSubjectEnquiryVehicleAssessmentStatusToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportSubjectEnquiryReimbursementStatusToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportSubjectDeleteAccountToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuContactSupportSubjectRequestPolicyDocumentsToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuInspectionToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuFindGarageToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuGetQuoteToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuGetQuoteSelectProductMotor',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuGetQuoteSelectProductHealth',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuReferFriendToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuReferFriendName',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuReferFriendMobile',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuReferFriendEmail',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuFindNetworkHospitalToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardName',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardMobile',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardEmail',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardVoucherAllToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardVoucherInsuranceProductToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardVoucherCharityToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardVoucherPetrolToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardVoucherKangarooToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardVoucherTravelAndLifestyleToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardVoucherFoodAndBeverageToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('MenuRoojaiRewardVoucherShoppingToDo',cellVal)
				}
				dataRowIndex+=1
				cellVal=dataInput.getValue(dataColIndex,dataRowIndex).trim()
				if(cellVal.length()>0){
					caseInput.put('PositiveCase',cellVal)
				}
				dataRowIndex=THAMyAccountNewbizMainType.INPUT_DATA_ROW_BEGIN
				dataCase.setInput(caseInput)
				this.lCaseList.add(dataCase)
			}
			this.IsValid=isValid
		}catch(Exception e){
			e.printStackTrace()
		}
	}
	public THAMyAccountNewbizMainType CaseData(){
		if((this.CurrentCase>0)&&(this.lCaseList.size()>0)){
			return this.lCaseList.get(this.CurrentCase-1)
		}
	}
	public Boolean SaveOutput(){
		Boolean lreturn=false
		THAMyAccountNewbizMainType caseData
		try{
			Integer dataColIndex=THAMyAccountNewbizMainType.OUTPUT_EXCEL_COL_BEGIN+(this.CurrentCase-1)
			Integer dataRowIndex=THAMyAccountNewbizMainType.OUTPUT_EXCEL_ROW_BEGIN
			if((this.CurrentCase>0)&&(this.lCaseList.size()>0)){
				caseData=this.lCaseList.get(this.CurrentCase-1)
				def xlsWorkbook=ExcelKeywords.getWorkbook(THAMyAccountNewbizMainType.OUTPUT_EXCEL_FILE_NAME)
				def xlsSheet=ExcelKeywords.getExcelSheet(xlsWorkbook,THAMyAccountNewbizMainType.OUTPUT_EXCEL_SHEET_NAME)
				Map lMapSaveOutput1=this.lSaveOutput1(xlsSheet,caseData,dataColIndex,dataRowIndex)
				if(!lMapSaveOutput1.Result){
					return lreturn
				}else{
					dataColIndex=lMapSaveOutput1.DataColIndex
					dataRowIndex=lMapSaveOutput1.DataRowIndex
				}
				Map lMapSaveOutput2=this.lSaveOutput2(xlsSheet,caseData,dataColIndex,dataRowIndex)
				if(!lMapSaveOutput2.Result){
					return lreturn
				}else{
					dataColIndex=lMapSaveOutput2.DataColIndex
					dataRowIndex=lMapSaveOutput2.DataRowIndex
				}
				IGNUemaHelper.saveExcelWorkbookByFileName(THAMyAccountNewbizMainType.OUTPUT_EXCEL_FILE_NAME,xlsWorkbook)
				lreturn=true
			}
		}catch(Exception e){
			e.printStackTrace()
			return lreturn
		}
		return lreturn
	}
	private Map lSaveOutput1(def xlsSheet,THAMyAccountNewbizMainType caseData,Integer numColIndex,Integer numRowIndex){
		Map lreturn=[:]
		try{
			Boolean lResult=false
			lreturn.put('Result',lResult)
			if(!xlsSheet){
				return lreturn
			}
			if(!caseData){
				return lreturn
			}
			Integer dataColIndex=numColIndex
			if(dataColIndex<0){
				return lreturn
			}
			Integer dataRowIndex=numRowIndex
			if(dataRowIndex<0){
				return lreturn
			}
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('BaseUrl').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MaximizeMode').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('WithAuth').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('AuthUser').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('AuthPassword').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('Language').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPaymentOpenTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPaymentChangeCreditCard').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPaymentMakePaymentCardOld').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPaymentMakePaymentCardNew').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuProfileToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuProfilePositiveCase').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileMaritalStatus').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfilePreferredLanguage').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileOccupation').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileAddressHouseBuildingNumber').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileAddressVillage').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileAddressSoiRoad').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileAddressPostcode').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileAddressProvince').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileAddressDistrict').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileAddressSubdistrict').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileTelephoneNumber').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileEmail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyCardSelectProductMotor').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyCardSelectProductHealth').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailTaxDeductionAccept').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailTaxDeductionEditToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailTaxDeductionEditHolderIsThai').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailTaxDeductionEditName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailTaxDeductionEditSurname').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailTaxDeductionEditIdentificationNumber').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyDetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuPolicyCompulsoryBuyCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuClaimToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuClaimDetailNonClosureToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuClaimDetailClosureStatusToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuClaimDetailClosureStatusUpdate').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuDocDownloadOpenInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuDocDownloadCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportSubjectRenewalToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportSubjectPolicyToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportSubjectClaimToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportSubjectEnquiryClaimHandlerToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportSubjectEnquiryVehicleAssessmentStatusToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportSubjectEnquiryReimbursementStatusToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportSubjectDeleteAccountToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuContactSupportSubjectRequestPolicyDocumentsToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuInspectionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuFindGarageToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuGetQuoteToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuGetQuoteSelectProductMotor').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuGetQuoteSelectProductHealth').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuReferFriendToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuReferFriendName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuReferFriendMobile').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuReferFriendEmail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuFindNetworkHospitalToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardMobile').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardEmail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardVoucherAllToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardVoucherInsuranceProductToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardVoucherCharityToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardVoucherPetrolToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardVoucherKangarooToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardVoucherTravelAndLifestyleToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardVoucherFoodAndBeverageToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('MenuRoojaiRewardVoucherShoppingToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PositiveCase').toString())
			dataRowIndex+=1
			lResult=true
			if(lResult){
				lreturn.put('DataColIndex',dataColIndex)
				lreturn.put('DataRowIndex',dataRowIndex)
				lreturn.put('Result',lResult)
			}
		}catch(Exception e){
			e.printStackTrace()
			return lreturn
		}
		return lreturn
	}
	private Map lSaveOutput2(def xlsSheet,THAMyAccountNewbizMainType caseData,Integer numColIndex,Integer numRowIndex){
		Map lreturn=[:]
		try{
			Boolean lResult=false
			lreturn.put('Result',lResult)
			if(!xlsSheet){
				return lreturn
			}
			if(!caseData){
				return lreturn
			}
			Integer dataColIndex=numColIndex
			if(dataColIndex<0){
				return lreturn
			}
			Integer dataRowIndex=numRowIndex
			if(dataRowIndex<0){
				return lreturn
			}
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ActualResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ResultMessage').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ActualAccountName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PaymentCardItemDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PaymentCardItemChangeCreditCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PaymentCardItemChangeCreditCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PaymentCardItemMakePaymentCardOldDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PaymentCardItemMakePaymentCardOldResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PaymentCardItemMakePaymentCardNewDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PaymentCardItemMakePaymentCardNewResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileEditDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ProfileEditResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem01DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem02DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem03DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem04DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem05DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem06DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem07DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem08DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem09DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailCardSelectedProductName').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailAdditionalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailHistoryToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailHistoryDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailPaymentToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailPaymentCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailPaymentOpenTermAndConditionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailPaymentTermAndCondition').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailDocDownloadToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailDocDownloadDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailDocDownloadResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailDocDownloadOpenInsuranceHandbookToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailDocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailTaxDeductionToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailTaxDeductionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailTaxDeductionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailECareCardToDo').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailECareCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyItem10DetailECareCardResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyCardSelectProductLineResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyCompulsoryBuyCardId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyCompulsoryBuyCardDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyCompulsoryBuyPaymentDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('PolicyCompulsoryBuyPaymentResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ClaimDetailNonClosureCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ClaimDetailNonClosureCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ClaimDetailClosureStatusCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ClaimDetailClosureStatusCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('DocDownloadInsuranceHandbook').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('DocDownloadCardSelectedId').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('DocDownloadCardSelectedDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('DocDownloadCardSelectedResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectRenewalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectRenewalResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectPolicyDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectPolicyResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectClaimDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectClaimResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectEnquiryClaimHandlerDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectEnquiryClaimHandlerResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectEnquiryVehicleAssessmentStatusDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectEnquiryVehicleAssessmentStatusResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectEnquiryReimbursementStatusDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectEnquiryReimbursementStatusResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectDeleteAccountDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectDeleteAccountResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectRequestPolicyDocumentsDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ContactSupportSubjectRequestPolicyDocumentsResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('InspectionDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('InspectionResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('FindGarageDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('FindGarageResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem01Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem01Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem02Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem02Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem03Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem03Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem04Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem04Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem05Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem05Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem06Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem06Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem07Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem07Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem08Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem08Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem09Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem09Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem10Detail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteItem10Result').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('GetQuoteSelectProductLineResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ReferFriendDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ReferFriendReferLink').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ReferFriendReferCode').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('ReferFriendResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('FindNetworkHospitalDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('FindNetworkHospitalResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointSummaryBefore').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointBalanceBefore').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointPendingBefore').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointAvailableBefore').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointTotalBefore').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyRewardBefore').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyHistoryBefore').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointSummaryAfter').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointBalanceAfter').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointPendingAfter').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointAvailableAfter').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyPointTotalAfter').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyRewardAfter').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardMyHistoryAfter').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherAllDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherAllAdditional').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherAllResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherInsuranceProductDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherInsuranceProductAdditional').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherInsuranceProductResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherCharityDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherCharityAdditional').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherCharityResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherPetrolDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherPetrolAdditional').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherPetrolResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherKangarooDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherKangarooAdditional').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherKangarooResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherTravelAndLifestyleDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherTravelAndLifestyleAdditional').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherTravelAndLifestyleResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherFoodAndBeverageDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherFoodAndBeverageAdditional').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherFoodAndBeverageResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherShoppingDetail').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherShoppingAdditional').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardVoucherShoppingResult').toString())
			dataRowIndex+=1
			ExcelKeywords.setValueToCellByIndex(xlsSheet,dataRowIndex,dataColIndex,caseData.Output.get('RoojaiRewardResult').toString())
			dataRowIndex+=1
			lResult=true
			if(lResult){
				lreturn.put('DataColIndex',dataColIndex)
				lreturn.put('DataRowIndex',dataRowIndex)
				lreturn.put('Result',lResult)
			}
		}catch(Exception e){
			e.printStackTrace()
			return lreturn
		}
		return lreturn
	}
}